Now working for xitomatl, with minor tweaking
One still needs to create dummy .sls files for libraries that have
only implementation-specific files. Doing just e.g.

% cp compat.ikarus.sls compat.sls

suffices.

darcs-hash:20081005174631-b4420-a5e339d734570f43d4059228578903f78c10d17e.gz

diff --git a/scripts/launch b/scripts/launch
--- a/scripts/launch
+++ b/scripts/launch
@@ -35,7 +35,14 @@ setup() {
     setup_no_symlinks $impl "$@" | while read source dest; do
 	dest=`echo "$dest" | sed "s,^,$target_dir/,g"`
 	mkdir -p `dirname "$dest"`
-	ln -s "$source" "$dest"
+	if [ -L "$dest" ] && [ `readlink "$dest"` = "$source" ]; then
+	    true # multiple include, that's ok
+	elif [ -e "$dest" ]; then
+	    echo "$dest already exists, cannot link to $source, aborting"
+	    exit 1
+	else
+	    ln -s "$source" "$dest"
+	fi
     done
 }
 
